// GENERATED by scripts/extract_data.py — do not edit by hand.
// Pain tracks are [excruciating, disabling, hurtful, annoying] in HOURS
// per average animal, over the species' study period.

export const PAIN_TRACKS = {
  "layers_conventional_cage": [
    0.05,
    431.41,
    4054.47,
    6721.17
  ],
  "layers_furnished_cage": [
    0.038,
    154.64,
    3151.39,
    6141.89
  ],
  "layers_cage_free": [
    0.04,
    156.04,
    1741.92,
    2076.79
  ],
  "broiler_conventional": [
    0.008388888888888888,
    50.27,
    333.6,
    324.67
  ],
  "broiler_bcc": [
    0.00155,
    17.26,
    255.7,
    339.31
  ],
  "slaughter_waterbath": [
    0.00033055555555555556,
    0.01933333333333333,
    0.017166666666666667,
    0.012277777777777778
  ],
  "slaughter_co2": [
    5.555555555555556e-06,
    0.00245,
    0.022000000000000002,
    0.016625
  ],
  "shrimp_lifetime": [
    0.14,
    5.88,
    519.77,
    4174.85
  ],
  "shrimp_ice_slurry": [
    0.006,
    0.0239,
    0.0003025,
    0.0
  ]
};

export const STUDY_PERIODS = {
  "layers": 546,
  "broilers": 42,
  "shrimp": 150
};

export const WELFARE_RANGES = {
  "pig": 0.512,
  "chicken": 0.327,
  "octopus": 0.238,
  "carp": 0.087,
  "bee": 0.071,
  "salmon": 0.055,
  "crayfish": 0.035,
  "shrimp": 0.029,
  "crab": 0.026
};

export const WELFARE_RANGE_INTERVALS = {
  "pig": [
    0.005,
    1.031
  ],
  "chicken": [
    0.002,
    0.856
  ],
  "octopus": [
    0.004,
    1.527
  ],
  "carp": [
    0,
    0.59
  ],
  "bee": [
    0,
    0.449
  ],
  "salmon": [
    0,
    0.495
  ],
  "crayfish": [
    0,
    0.503
  ],
  "shrimp": [
    0,
    1.095
  ],
  "crab": [
    0,
    0.444
  ]
};

export const SPECIES = [
  {
    "key": "fish",
    "name": "Farmed fish",
    "alive": 113575686130,
    "wrKey": "carp",
    "wrProxy": "carp",
    "painSource": "assumption",
    "anchor": "broilers",
    "multiple": 0.4
  },
  {
    "key": "broilers",
    "name": "Broilers",
    "alive": 10653860086,
    "wrKey": "chicken",
    "wrProxy": null,
    "painSource": "track",
    "track": "broiler_conventional",
    "slaughterTrack": "slaughter_waterbath",
    "period": "broilers"
  },
  {
    "key": "layers",
    "name": "Layers",
    "alive": 8151106802,
    "wrKey": "chicken",
    "wrProxy": null,
    "painSource": "track",
    "track": "layers_conventional_cage",
    "slaughterTrack": null,
    "period": "layers"
  },
  {
    "key": "shrimp",
    "name": "Shrimp",
    "alive": 230000000000,
    "wrKey": "shrimp",
    "wrProxy": null,
    "painSource": "track",
    "track": "shrimp_lifetime",
    "slaughterTrack": null,
    "period": "shrimp"
  },
  {
    "key": "pigs",
    "name": "Pigs",
    "alive": 969795901,
    "wrKey": "pig",
    "wrProxy": null,
    "painSource": "assumption",
    "anchor": "broilers",
    "multiple": 0.5
  },
  {
    "key": "ducks",
    "name": "Ducks",
    "alive": 1267793000,
    "wrKey": "chicken",
    "wrProxy": "chicken",
    "painSource": "proxy",
    "anchor": "broilers",
    "multiple": 1.0
  },
  {
    "key": "turkeys",
    "name": "Turkeys",
    "alive": 231329000,
    "wrKey": "chicken",
    "wrProxy": "chicken",
    "painSource": "proxy",
    "anchor": "broilers",
    "multiple": 1.0
  },
  {
    "key": "cattle",
    "name": "Cattle & buffalo",
    "alive": 1785366233,
    "wrKey": "pig",
    "wrProxy": "pig",
    "painSource": "proxy",
    "anchor": "broilers",
    "multiple": 0.0812
  },
  {
    "key": "sheep",
    "name": "Sheep & goats",
    "alive": 2450319535,
    "wrKey": "pig",
    "wrProxy": "pig",
    "painSource": "proxy",
    "anchor": "broilers",
    "multiple": 0.0812
  }
];

export const COUNTRIES = [
  [
    "China",
    "LM",
    484400000,
    97700000,
    74100000,
    34300000,
    34800000,
    3000,
    105200000,
    322400000
  ],
  [
    "India",
    "LM",
    75500000,
    33700000,
    15000000,
    660000,
    1400000,
    0,
    306500000,
    231700000
  ],
  [
    "Indonesia",
    "LM",
    51100000,
    11900000,
    22000000,
    569000,
    2500000,
    0,
    19800000,
    35200000
  ],
  [
    "United States",
    "US",
    3000000,
    16700000,
    51300000,
    5900000,
    336000,
    3100000,
    88800000,
    7700000
  ],
  [
    "Brazil",
    "LA",
    6600000,
    7300000,
    38900000,
    3400000,
    142000,
    249000,
    240300000,
    34700000
  ],
  [
    "Bangladesh",
    "LM",
    33800000,
    10100000,
    1900000,
    0,
    2800000,
    0,
    26400000,
    30800000
  ],
  [
    "Vietnam",
    "LM",
    28800000,
    5000000,
    5100000,
    2000000,
    3700000,
    0,
    8500000,
    3100000
  ],
  [
    "Russia",
    "RW",
    1500000,
    10400000,
    21800000,
    2200000,
    917000,
    376000,
    17500000,
    20800000
  ],
  [
    "Egypt",
    "RW",
    24900000,
    3300000,
    8100000,
    2000,
    191000,
    98000,
    4600000,
    3000000
  ],
  [
    "Other countries",
    "RW",
    2771000,
    9435000,
    15207000,
    1892000,
    108000,
    141000,
    177000000,
    435000000
  ],
  [
    "Turkey",
    "LM",
    10700000,
    6800000,
    10400000,
    0,
    18000,
    142000,
    16600000,
    52400000
  ],
  [
    "Mexico",
    "LA",
    631000,
    12100000,
    12900000,
    1500000,
    0,
    160000,
    36600000,
    17700000
  ],
  [
    "Philippines",
    "LM",
    14300000,
    4300000,
    6300000,
    762000,
    568000,
    24000,
    5400000,
    3900000
  ],
  [
    "Japan",
    "HA",
    4800000,
    9200000,
    6500000,
    699000,
    0,
    0,
    4000000,
    33000
  ],
  [
    "Iran",
    "LM",
    5200000,
    3900000,
    10900000,
    0,
    67000,
    84000,
    5600000,
    70400000
  ],
  [
    "Thailand",
    "LM",
    7000000,
    3300000,
    6700000,
    602000,
    651000,
    0,
    5500000,
    522000
  ],
  [
    "Pakistan",
    "LM",
    1500000,
    6700000,
    8200000,
    0,
    158000,
    0,
    100400000,
    117100000
  ],
  [
    "Poland",
    "EU",
    242000,
    2900000,
    8300000,
    762000,
    291000,
    635000,
    6300000,
    331000
  ],
  [
    "Republic of Korea",
    "HA",
    3000000,
    2500000,
    5900000,
    865000,
    275000,
    0,
    4000000,
    324000
  ],
  [
    "Myanmar",
    "LM",
    8300000,
    652000,
    2200000,
    608000,
    483000,
    0,
    12900000,
    2800000
  ],
  [
    "Colombia",
    "LA",
    2000000,
    3200000,
    5400000,
    830000,
    0,
    0,
    29800000,
    2900000
  ],
  [
    "Malaysia",
    "LM",
    1700000,
    5100000,
    4000000,
    97000,
    402000,
    0,
    799000,
    479000
  ],
  [
    "Spain",
    "EU",
    1600000,
    2600000,
    3900000,
    2600000,
    0,
    0,
    6300000,
    15900000
  ],
  [
    "France",
    "EU",
    419000,
    3200000,
    4100000,
    920000,
    797000,
    579000,
    16800000,
    7900000
  ],
  [
    "United Kingdom",
    "EU",
    884000,
    2400000,
    5700000,
    365000,
    62000,
    105000,
    9600000,
    31900000
  ],
  [
    "Peru",
    "LA",
    2200000,
    1700000,
    5100000,
    270000,
    0,
    0,
    5900000,
    13000000
  ],
  [
    "South Africa",
    "RW",
    13000,
    3100000,
    6000000,
    103000,
    18000,
    23000,
    12200000,
    26600000
  ],
  [
    "Cambodia",
    "LM",
    8000000,
    407000,
    204000,
    159000,
    373000,
    0,
    3300000,
    0
  ],
  [
    "Nigeria",
    "RW",
    3000000,
    3700000,
    1500000,
    739000,
    0,
    0,
    20900000,
    140700000
  ],
  [
    "Germany",
    "EU",
    219000,
    3200000,
    3300000,
    1700000,
    67000,
    378000,
    10800000,
    1700000
  ],
  [
    "Ukraine",
    "EU",
    102000,
    3700000,
    3900000,
    386000,
    372000,
    58000,
    2300000,
    941000
  ],
  [
    "Argentina",
    "LA",
    26000,
    2800000,
    4600000,
    459000,
    112000,
    120000,
    54200000,
    16700000
  ],
  [
    "Canada",
    "RW",
    609000,
    2000000,
    3400000,
    1100000,
    63000,
    237000,
    11300000,
    877000
  ],
  [
    "Chile",
    "LA",
    3700000,
    677000,
    1800000,
    220000,
    0,
    1000000,
    3000000,
    1600000
  ],
  [
    "Italy",
    "EU",
    934000,
    2400000,
    2900000,
    715000,
    0,
    0,
    6400000,
    7500000
  ],
  [
    "Saudi Arabia",
    "HA",
    837000,
    1900000,
    4100000,
    0,
    0,
    0,
    646000,
    25300000
  ],
  [
    "Morocco",
    "RW",
    25000,
    2000000,
    3600000,
    1000,
    0,
    602000,
    2900000,
    26300000
  ],
  [
    "Norway",
    "EU",
    5100000,
    238000,
    473000,
    57000,
    5000,
    17000,
    876000,
    2300000
  ],
  [
    "Australia",
    "RW",
    374000,
    629000,
    4400000,
    193000,
    49000,
    38000,
    29900000,
    76200000
  ],
  [
    "Greece",
    "EU",
    4600000,
    256000,
    561000,
    61000,
    0,
    0,
    627000,
    10600000
  ],
  [
    "Taiwan",
    "HA",
    0,
    2000000,
    2400000,
    402000,
    306000,
    3000,
    159000,
    108000
  ],
  [
    "Netherlands",
    "EU",
    101000,
    1600000,
    2500000,
    809000,
    24000,
    25000,
    3700000,
    1200000
  ],
  [
    "Algeria",
    "RW",
    109000,
    1900000,
    2400000,
    0,
    3000,
    318000,
    1800000,
    36900000
  ],
  [
    "Uzbekistan",
    "LM",
    980000,
    2700000,
    385000,
    3000,
    0,
    31000,
    14100000,
    24100000
  ],
  [
    "Israel",
    "HA",
    211000,
    364000,
    3000000,
    10000,
    7000,
    130000,
    580000,
    614000
  ],
  [
    "Belarus",
    "EU",
    38000,
    1000000,
    2100000,
    194000,
    78000,
    59000,
    4200000,
    126000
  ],
  [
    "Nepal",
    "LM",
    948000,
    787000,
    1500000,
    106000,
    56000,
    0,
    7800000,
    15000000
  ],
  [
    "Ghana",
    "RW",
    1600000,
    1100000,
    577000,
    72000,
    0,
    0,
    2300000,
    15200000
  ],
  [
    "Guatemala",
    "LA",
    203000,
    1500000,
    1400000,
    229000,
    0,
    0,
    4200000,
    733000
  ],
  [
    "Venezuela",
    "LA",
    36000,
    574000,
    2000000,
    238000,
    0,
    0,
    16500000,
    1800000
  ],
  [
    "Laos",
    "LM",
    1800000,
    156000,
    299000,
    353000,
    155000,
    0,
    3800000,
    787000
  ],
  [
    "Romania",
    "EU",
    78000,
    556000,
    1800000,
    246000,
    0,
    0,
    1800000,
    11700000
  ],
  [
    "Mozambique",
    "RW",
    41000,
    2100000,
    295000,
    92000,
    110000,
    7000,
    2400000,
    4300000
  ],
  [
    "Uganda",
    "RW",
    1200000,
    629000,
    419000,
    374000,
    0,
    0,
    15200000,
    22500000
  ],
  [
    "Tunisia",
    "RW",
    804000,
    570000,
    646000,
    0,
    0,
    562000,
    584000,
    7400000
  ],
  [
    "Kazakhstan",
    "LM",
    43000,
    1300000,
    1100000,
    38000,
    4000,
    86000,
    6600000,
    18700000
  ],
  [
    "Dominican Republic",
    "LA",
    33000,
    1000000,
    1400000,
    67000,
    0,
    0,
    3100000,
    486000
  ],
  [
    "Belgium",
    "EU",
    3000,
    618000,
    1400000,
    420000,
    0,
    0,
    2200000,
    0
  ],
  [
    "Tanzania",
    "RW",
    361000,
    1000000,
    902000,
    42000,
    57000,
    0,
    37900000,
    37000000
  ],
  [
    "Zambia",
    "RW",
    881000,
    884000,
    304000,
    93000,
    0,
    0,
    4600000,
    4900000
  ],
  [
    "Hungary",
    "EU",
    122000,
    440000,
    1100000,
    203000,
    115000,
    106000,
    877000,
    938000
  ],
  [
    "Denmark",
    "EU",
    242000,
    257000,
    652000,
    887000,
    3000,
    11000,
    1400000,
    153000
  ],
  [
    "Bolivia",
    "LA",
    28000,
    626000,
    1100000,
    249000,
    28000,
    0,
    11100000,
    9800000
  ],
  [
    "Portugal",
    "EU",
    174000,
    491000,
    1100000,
    170000,
    0,
    0,
    1500000,
    2600000
  ],
  [
    "Yemen",
    "LM",
    0,
    618000,
    1300000,
    0,
    0,
    0,
    1900000,
    20300000
  ],
  [
    "Sri Lanka",
    "LM",
    364000,
    477000,
    1000000,
    8000,
    1000,
    0,
    1400000,
    363000
  ],
  [
    "Cote d'Ivoire",
    "RW",
    76000,
    908000,
    737000,
    36000,
    0,
    0,
    1900000,
    6600000
  ],
  [
    "Jordan",
    "LM",
    19000,
    93000,
    1600000,
    0,
    0,
    0,
    79000,
    3700000
  ],
  [
    "Ecuador",
    "LA",
    56000,
    446000,
    1100000,
    77000,
    15000,
    12000,
    3700000,
    591000
  ],
  [
    "Malawi",
    "RW",
    121000,
    345000,
    371000,
    704000,
    0,
    0,
    2200000,
    12900000
  ],
  [
    "Sudan",
    "RW",
    135000,
    915000,
    460000,
    0,
    0,
    0,
    30700000,
    71400000
  ],
  [
    "Iraq",
    "LM",
    124000,
    284000,
    1100000,
    0,
    0,
    0,
    2400000,
    8200000
  ],
  [
    "DPR Korea",
    "LM",
    141000,
    801000,
    65000,
    186000,
    302000,
    0,
    573000,
    4100000
  ],
  [
    "Honduras",
    "LA",
    429000,
    244000,
    762000,
    36000,
    0,
    0,
    2900000,
    42000
  ],
  [
    "Azerbaijan",
    "LM",
    4000,
    670000,
    675000,
    0,
    0,
    62000,
    2500000,
    7100000
  ],
  [
    "Burkina Faso",
    "RW",
    11000,
    922000,
    268000,
    116000,
    0,
    0,
    10100000,
    22300000
  ],
  [
    "Senegal",
    "RW",
    9000,
    705000,
    511000,
    39000,
    0,
    0,
    3800000,
    14700000
  ],
  [
    "Czechia",
    "EU",
    89000,
    413000,
    650000,
    106000,
    0,
    0,
    1400000,
    208000
  ],
  [
    "Croatia",
    "EU",
    663000,
    132000,
    372000,
    67000,
    1000,
    15000,
    415000,
    625000
  ],
  [
    "Madagascar",
    "RW",
    19000,
    333000,
    377000,
    181000,
    194000,
    102000,
    7500000,
    3000000
  ],
  [
    "Austria",
    "EU",
    57000,
    409000,
    516000,
    196000,
    0,
    0,
    1800000,
    489000
  ],
  [
    "Sweden",
    "EU",
    36000,
    458000,
    561000,
    103000,
    0,
    0,
    1400000,
    339000
  ],
  [
    "Paraguay",
    "LA",
    173000,
    466000,
    320000,
    104000,
    57000,
    9000,
    13500000,
    441000
  ],
  [
    "Serbia",
    "EU",
    28000,
    479000,
    436000,
    167000,
    4000,
    3000,
    725000,
    1900000
  ],
  [
    "Syria",
    "LM",
    18000,
    622000,
    465000,
    0,
    2000,
    6000,
    848000,
    20800000
  ],
  [
    "Mali",
    "RW",
    108000,
    531000,
    445000,
    7000,
    0,
    0,
    13600000,
    55500000
  ],
  [
    "Cuba",
    "LA",
    133000,
    695000,
    120000,
    136000,
    0,
    0,
    3400000,
    2000000
  ],
  [
    "Kenya",
    "RW",
    281000,
    582000,
    147000,
    66000,
    0,
    0,
    21900000,
    58200000
  ],
  [
    "Libya",
    "RW",
    0,
    381000,
    695000,
    0,
    0,
    0,
    211000,
    10200000
  ],
  [
    "Ethiopia",
    "RW",
    7000,
    920000,
    94000,
    3000,
    0,
    0,
    70900000,
    93500000
  ],
  [
    "El Salvador",
    "LA",
    171000,
    361000,
    443000,
    19000,
    0,
    0,
    746000,
    20000
  ],
  [
    "Angola",
    "RW",
    35000,
    193000,
    404000,
    280000,
    0,
    0,
    5200000,
    5600000
  ],
  [
    "Guinea",
    "RW",
    16000,
    697000,
    44000,
    14000,
    0,
    0,
    8800000,
    8200000
  ]
];

export const COUNTRY_COLS = {
  "fish": 2,
  "layers": 3,
  "broilers": 4,
  "pigs": 5,
  "ducks": 6,
  "turkeys": 7,
  "cattle": 8,
  "sheep": 9
};

export const GEOGRAPHIES = {
  "US": {
    "name": "United States"
  },
  "EU": {
    "name": "Europe"
  },
  "LA": {
    "name": "Latin America"
  },
  "LM": {
    "name": "LMIC Asia"
  },
  "HA": {
    "name": "HIC Asia"
  },
  "RW": {
    "name": "Rest of world"
  }
};

export const COUNTRY_TABLE_RATES = {
  "fish": 0.0072,
  "layers": 0.042,
  "broilers": 0.042,
  "pigs": 0.078,
  "ducks": 0.042,
  "turkeys": 0.042
};

export const REFORM_DEFS = [
  {
    "key": "cagefree",
    "label": "Layers \u2014 conventional cage to cage-free",
    "species": "layers",
    "from": "layers_conventional_cage",
    "to": "layers_cage_free",
    "provenance": "measured"
  },
  {
    "key": "furnished",
    "label": "Layers \u2014 conventional cage to furnished cage",
    "species": "layers",
    "from": "layers_conventional_cage",
    "to": "layers_furnished_cage",
    "provenance": "measured"
  },
  {
    "key": "bcc",
    "label": "Broilers \u2014 conventional to BCC",
    "species": "broilers",
    "from": "broiler_conventional",
    "to": "broiler_bcc",
    "component": "broiler_conventional",
    "provenance": "measured"
  },
  {
    "key": "stunning",
    "label": "Broiler slaughter \u2014 waterbath to multi-stage CO\u2082",
    "species": "broilers",
    "from": "slaughter_waterbath",
    "to": "slaughter_co2",
    "component": "slaughter_waterbath",
    "provenance": "measured"
  },
  {
    "key": "shrimpstun",
    "label": "Shrimp \u2014 ice slurry to electrical stunning",
    "species": "shrimp",
    "from": "shrimp_lifetime",
    "to": null,
    "subtract": "shrimp_ice_slurry",
    "provenance": "measured"
  },
  {
    "key": "pigcrates",
    "label": "Pigs \u2014 gestation crates to group housing",
    "species": "pigs",
    "fixedReduction": 0.5,
    "provenance": "assumption"
  },
  {
    "key": "fishstun",
    "label": "Fish \u2014 pre-slaughter stunning",
    "species": "fish",
    "fixedReduction": 0.0058,
    "provenance": "assumption"
  }
];

