// Regenerates map.js: world country outlines, pre-projected to SVG paths so
// the page needs no map library at runtime. Run from a scratch directory:
//   npm install d3-geo topojson-client world-atlas
//   N=$(node -e 'import("<repo>/data.js").then(d=>process.stdout.write(d.COUNTRIES.map(r=>r[0]).join("|")))')
//   node <repo>/scripts/build_map.mjs "$N" <repo>/map.js
// It prints any source-table country with no matching outline; fix those in
// `alias` below.
import { geoNaturalEarth1, geoPath } from "d3-geo";
import { feature } from "topojson-client";
import { readFileSync, writeFileSync } from "fs";
const topo = JSON.parse(readFileSync("node_modules/world-atlas/countries-110m.json"));
const fc = feature(topo, topo.objects.countries);
fc.features = fc.features.filter(f => f.properties.name !== "Antarctica");
const ours = process.argv[2].split("|");
const alias = { "United States of America": "United States", "South Korea": "Republic of Korea",
  "North Korea": "DPR Korea", "Côte d'Ivoire": "Cote d'Ivoire", "Dominican Rep.": "Dominican Republic",
  "Czech Rep.": "Czechia", "Lao PDR": "Laos" };
const W = 960, H = 470;
const proj = geoNaturalEarth1().fitExtent([[4, 4], [W - 4, H - 4]], fc);
const path = geoPath(proj).digits(1);
const out = fc.features.map(f => {
  const n = f.properties.name; const name = alias[n] ?? n;
  return { name: ours.includes(name) ? name : null, label: n, d: path(f) };
});
const matched = new Set(out.filter(o => o.name).map(o => o.name));
console.log("unmatched ours:", ours.filter(n => !matched.has(n) && n !== "Other countries"));
writeFileSync(process.argv[3], "// Generated by scripts/build_map.mjs from world-atlas 110m (Natural Earth,\n// public domain), Natural Earth projection. Do not edit by hand.\n" +
  "export const WORLD = " + JSON.stringify({ viewBox: `0 0 ${W} ${H}`, countries: out }) + ";\n");
