// Regenerates icons.js from the silhouettes in Icons/ (Noun Project).
// Run: node scripts/build_icons.mjs
// Each species maps to one source file; `flip` mirrors left-facing icons so
// every animal on the page faces the same way.
import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const MAP = {
  layers:   { file: "noun_Chicken_6985354.svg" },   // hen
  broilers: { file: "noun_Chicken_6985370.svg" },   // rooster
  cattle:   { file: "noun_Cow_2020629.svg" },
  fish:     { file: "noun_Fish_2020627.svg" },
  sheep:    { file: "noun_Goat_6985368.svg", flip: true },
  pigs:     { file: "noun_Pig_7950526.svg" },
  shrimp:   { file: "noun_Shrimp_8366895.svg", flip: true },
  turkeys:  { file: "noun_Turkey_7729512.svg", flip: true },
  ducks:    { file: "noun_Duck_8354232.svg", flip: true },
};
const out = {};
for (const [key, { file, flip = false }] of Object.entries(MAP)) {
  const svg = readFileSync(join(ROOT, "Icons", file), "utf8");
  const viewBox = svg.match(/viewBox="([^"]+)"/)[1];
  const d = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map(m => m[1]);
  if (!d.length) throw new Error("no paths in " + file);
  out[key] = { viewBox, d, flip };
}
writeFileSync(join(ROOT, "icons.js"),
  "// Generated by scripts/build_icons.mjs from Icons/ (Noun Project). Do not edit.\n" +
  "export const ICONS = " + JSON.stringify(out) + ";\n");
console.log("wrote icons.js:", Object.keys(out).join(", "));
